# AppVeyor CI
# https://www.appveyor.com/docs

environment:
  matrix:
    # For Python versions available on AppVeyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    # Fails due to missing pywin32 for Python 3.6:
    # <https://ci.appveyor.com/project/rutsky/setuptools-trial/build/1.0.42/job/bhd6nfpps5ahn5k0>
    #- PYTHON: "C:\\Python36"

install:
  # Upgrade pip and setuptools. Just in case.
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools"
  # Twisted requires pywin32 on Windows in order to spawn processes.
  - "%PYTHON%\\python.exe -m pip install pypiwin32"
  - "%PYTHON%\\python.exe -m pip install -rtest-requirements.txt"
  - "set VIRTUALENV_FIXTURE_EXECUTABLE=%PYTHON%\\Scripts\\virtualenv.exe"

build: false

test_script:
  - "%PYTHON%\\python.exe setup.py test"
